### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by Zalkus** [dseeler/bank-xp-value#10]
2 things here. 1. Mithril ore is not showing up as a smithing item. 2. Can you have logs show up as construction/fletching xp in the calcs? It seems weird that banked teaks and mahoganies arent con xp and banked yew and magics arent fletching as well.

**Comment by dseeler** [comment]
1. Mithril ore is not included because it must be used with coal in order to get smithing xp -- it doesn't have an individual xp value. 
2. Right now, the way the plugin works is that there can only be one xp value associated with each item. That said, I gave logs the firemaking xp values and not fletching/cons because they're more used for firemaking (idk if that's still the case). I agree with your point though and it can definitely be revamped in the future.
